import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const sriracha = localFont({
  src: "./fonts/Sriracha-Regular.ttf",
  variable: "--font-sriracha",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sriracha.variable} font-sans`}>{children}</body>
    </html>
  );
}
